import { hostConfigurationSchema } from '@treeseed/sdk/deployment';
import { z } from 'zod';
import { hostDevelopmentActivationSchema } from './host-development.js';

const supervisorOperationUnion = z.discriminatedUnion('operation', [
	z.object({ operation: z.literal('supervisor.ping') }).strict(),
	z.object({ operation: z.literal('security.plan') }).strict(),
	z.object({ operation: z.literal('security.status') }).strict(),
	z.object({ operation: z.literal('security.verify') }).strict(),
	z.object({ operation: z.literal('security.initialize'), recoveryBundle: z.string().startsWith('/').max(4_096), recoveryPassphrase: z.string().min(12).max(1_024), confirm: z.literal(true) }).strict(),
	z.object({ operation: z.literal('provider.credentials.status'), credentialIds: z.array(z.string().regex(/^[a-z][a-z0-9.-]{1,127}$/u)).max(128) }).strict(),
	z.object({ operation: z.literal('provider.credential.initialize'), initializerId: z.string().regex(/^[a-z][a-z0-9.-]{1,63}$/u), sourceId: z.string().regex(/^[a-z][a-z0-9.-]{1,63}$/u), secret: z.string().min(1).max(1_048_576) }).strict(),
	z.object({ operation: z.literal('security.rotate'), target: z.enum(['volume', 'credentials', 'diagnostics']), recoveryBundle: z.string().startsWith('/').max(4_096), recoveryPassphrase: z.string().min(12).max(1_024), newRecoveryBundle: z.string().startsWith('/').max(4_096), newRecoveryPassphrase: z.string().min(12).max(1_024), confirm: z.literal(true) }).strict(),
	z.object({ operation: z.literal('security.recovery.verify'), recoveryBundle: z.string().startsWith('/').max(4_096), recoveryPassphrase: z.string().min(12).max(1_024) }).strict(),
	z.object({ operation: z.literal('sandbox.status') }).strict(),
	z.object({ operation: z.literal('sandbox.doctor') }).strict(),
	z.object({ operation: z.literal('sandbox.trust-anchor.repair') }).strict(),
	z.object({ operation: z.literal('sandbox.guest-trust.digests') }).strict(),
	z.object({ operation: z.literal('sandbox.guest-trust.bind'), digest: z.string().regex(/^sha256:[a-f0-9]{64}$/u) }).strict(),
	z.object({ operation: z.literal('sandbox.guest-image.import'), archivePath: z.string().startsWith('/').max(4_096), image: z.string().regex(/^(?:docker\.io\/)?treeseed\/sandbox-[a-z0-9._-]+:local$/u) }).strict(),
	z.object({ operation: z.literal('apt.refresh'), track: z.enum(['stable', 'development']), updateCore: z.boolean() }).strict(),
	z.object({ operation: z.literal('apt.install'), packages: z.array(z.string().regex(/^treeseed(?:-[a-z0-9-]+)?(?:(?:=[0-9A-Za-z.+:~-]+)|(?:\/(?:stable|development)))?$/u)).min(1) }).strict(),
	z.object({ operation: z.literal('compose.activate'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), files: z.array(z.string().min(1)).min(1), projectName: z.string().regex(/^treeseed-[a-z0-9-]+$/u), services: z.array(z.string().regex(/^[a-z][a-z0-9.-]+$/u)).min(1).optional(), waitTimeoutSeconds: z.number().int().min(1).max(3_600) }).strict(),
	z.object({ operation: z.literal('compose.stop'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), files: z.array(z.string().min(1)).min(1), projectName: z.string().regex(/^treeseed-[a-z0-9-]+$/u) }).strict(),
	z.object({ operation: z.literal('compose.status'), projectName: z.string().regex(/^treeseed-[a-z0-9-]+$/u) }).strict(),
	z.object({ operation: z.literal('compose.remove'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), files: z.array(z.string().min(1)).min(1), projectName: z.string().regex(/^treeseed-[a-z0-9-]+$/u) }).strict(),
	z.object({ operation: z.literal('ai.gpu.gate'), role: z.enum(['inference', 'training']), action: z.enum(['open', 'close', 'status']), files: z.array(z.string().min(1)).min(1) }).strict(),
	z.object({ operation: z.literal('ai.gpu.workload'), role: z.enum(['inference', 'training']), action: z.enum(['start', 'stop', 'status', 'warm']), files: z.array(z.string().min(1)).min(1), waitTimeoutSeconds: z.number().int().min(1).max(3_600).default(900) }).strict(),
	z.object({ operation: z.literal('ai.mode.credentials.ensure') }).strict(),
	z.object({ operation: z.literal('storage.r2.status'), teamId: z.string().min(1).max(256) }).strict(),
	z.object({ operation: z.literal('storage.r2.install'), teamId: z.string().min(1).max(256), accountId: z.string().regex(/^[a-f0-9]{32}$/u), bucket: z.string().regex(/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/u),
		bootstrapToken: z.string().min(16).max(16_384), managementToken: z.string().min(16).max(16_384), accessKeyId: z.string().min(8).max(256), secretAccessKey: z.string().min(16).max(256),
		privacyTokenId: z.string().regex(/^[a-f0-9]{32}$/u), publisherTokenId: z.string().regex(/^[a-f0-9]{32}$/u) }).strict(),
	z.object({ operation: z.literal('component.configure'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), connectionEnvironment: z.record(z.string().regex(/^[A-Z][A-Z0-9_]{0,127}$/u), z.string().max(16_384)), secretFileIds: z.array(z.string().regex(/^[a-z0-9][a-z0-9._-]{0,127}$/u)).max(128).optional(), sandboxGuestImageDigest: z.string().regex(/^sha256:[a-f0-9]{64}$/u).optional() }).strict(),
	z.object({ operation: z.literal('development.environment'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), connectionEnvironment: z.record(z.string().regex(/^[A-Z][A-Z0-9_]{0,127}$/u), z.string().max(16_384)), secretRefs: z.record(z.string().regex(/^[A-Z][A-Z0-9_]{0,127}$/u), z.string().regex(/^[a-z0-9][a-z0-9._-]{0,127}$/u)) }).strict(),
	z.object({ operation: z.literal('host.development.activate'), activation: hostDevelopmentActivationSchema }).strict(),
	z.object({ operation: z.literal('host.development.status') }).strict(),
	z.object({ operation: z.literal('host.development.deactivate') }).strict(),
	z.object({ operation: z.literal('component.reset-unaccepted'), componentId: z.string().regex(/^[a-z][a-z0-9.-]+$/u) }).strict(),
	z.object({ operation: z.literal('provider.enroll'), connectionId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), teamId: z.string().min(1).max(256), controlPlaneUrl: z.string().url().startsWith('https://'), controlPlaneAudience: z.string().url().startsWith('https://'), registrationSecretId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), offer: z.object({ maxConcurrentRunners: z.number().int().positive().max(1_024), capabilities: z.array(z.string().min(1).max(128)).max(256), metadata: z.record(z.union([z.string(), z.number(), z.boolean()])).optional() }).strict(), files: z.array(z.string().min(1)).min(1), projectName: z.literal('treeseed-agent') }).strict(),
	z.object({ operation: z.literal('provider.enrollment-handoff'), payload: z.discriminatedUnion('action', [
		z.object({ action: z.literal('begin'), connectionId: z.string().regex(/^[a-z][a-z0-9.-]+$/u), teamId: z.string().min(1).max(256), controlPlaneUrl: z.string().url(), controlPlaneAudience: z.string().url(), enrollmentToken: z.string().min(1).max(16_384) }).strict(),
		z.object({ action: z.literal('complete'), connectionId: z.string().regex(/^[a-z][a-z0-9.-]+$/u) }).strict(),
	]), files: z.array(z.string().min(1)).min(1), projectName: z.literal('treeseed-agent') }).strict(),
	z.object({ operation: z.literal('edge.apply'), caddyfile: z.string().min(1), aliases: z.array(z.string().endsWith('.localhost')).min(1) }).strict(),
	z.object({ operation: z.literal('systemd.control'), unit: z.enum(['treeseed-manager-api.service', 'treeseed-manager-reconcile.service', 'treeseed-edge.service']), action: z.enum(['start', 'stop', 'restart', 'reload']) }).strict(),
	z.object({ operation: z.literal('recovery.restore'), generation: z.number().int().positive() }).strict(),
	z.object({ operation: z.literal('backup.create'), generation: z.number().int().positive() }).strict(),
	z.object({ operation: z.literal('backup.inspect'), generation: z.number().int().positive() }).strict(),
	z.object({ operation: z.literal('backup.list') }).strict(),
	z.object({ operation: z.literal('platform.reset'), componentDataRoot: z.union([
		z.literal('/var/lib/treeseed/components'),
		z.string().startsWith('/').regex(/\/\.treeseed\/data$/u),
	]) }).strict(),
	z.object({ operation: z.literal('cli.configure'), controlPlaneUrl: z.string().url().refine((value) => value.startsWith('https://') || value.startsWith('http://127.0.0.1'), 'Control-plane URL must use HTTPS or loopback HTTP.') }).strict(),
	z.object({ operation: z.literal('manager.restart') }).strict(),
	z.object({ operation: z.literal('configuration.replace'), configuration: hostConfigurationSchema }).strict(),
	z.object({ operation: z.literal('configuration.adopt'), configuration: hostConfigurationSchema }).strict(),
	z.object({ operation: z.literal('configuration.recover'), configuration: hostConfigurationSchema }).strict(),
	z.object({ operation: z.literal('pki.enroll'), clientId: z.string().regex(/^client-[a-z0-9-]{8,64}$/u) }).strict(),
]);

export const supervisorOperationSchema = supervisorOperationUnion;

export type SupervisorOperation = z.infer<typeof supervisorOperationSchema>;
