#!/bin/sh
set -eu
install -d -o root -g root -m 0755 /etc/kata-containers /usr/local/bin
ln -sfn /opt/kata/runtime-rs/bin/containerd-shim-kata-v2 /usr/local/bin/containerd-shim-kata-v2
ln -sfn /opt/kata/share/defaults/kata-containers/runtime-rs/configuration-qemu-runtime-rs.toml /etc/kata-containers/configuration.toml
systemctl restart containerd.service
exit 0
